export const PortfolioData = [
  {
    id: 1,
    type: "web",
    featured: true,
    title: "Photocelos",
    img: "assets/portfolio/web/photocelos.jpg",
    desc: "Este projecto tem por objectivo dar a conhecer o patrimonio do concelho de Barcelos",
  },
  {
    id: 2,
    type: "web",
    featured: false,
    title: "Alotecnica",
    img: "assets/portfolio/web/alotecnica.jpeg",
    desc: "",
  },
  {
    id: 3,
    type: "web",
    featured: false,
    title: "Belofer",
    img: "assets/portfolio/web/belofer.png",
    desc: "A Belofer consultou-nos para a criação do seu web site. Um website simples mas elegante.",
  },
  {
    id: 4,
    type: "web",
    featured: false,
    title: "Credivida",
    img: "assets/portfolio/web/credivida.png",
    desc: "",
  },
  {
    id: 5,
    type: "web",
    featured: true,
    title: "Motocavaquinhos",
    img: "assets/portfolio/web/motocavaquinho.png",
    desc: "",
  },
  {
    id: 6,
    type: "web",
    featured: false,
    title: "Ritmolouco",
    img: "assets/portfolio/web/ritmolouco.jpg",
    desc: "",
  },
  {
    id: 7,
    type: "web",
    featured: false,
    title: "Tecniwall",
    img: "assets/portfolio/web/tecniwall.jpg",
    desc: "",
  },
  {
    id: 8,
    type: "web",
    featured: false,
    title: "Vouga Plazza",
    img: "assets/portfolio/web/vouga-plazza.png",
    desc: "",
  },
  {
    id: 9,
    type: "web",
    featured: false,
    title: "Ritual Restaurante",
    img: "assets/portfolio/web/ritual-restaurante.png",
    desc: "",
  },
  {
    id: 10,
    type: "web",
    featured: false,
    title: "Paula Soares da Costa",
    img: "assets/portfolio/web/paulasoarescosta.png",
    desc: "",
  },
  {
    id: 11,
    type: "web",
    featured: false,
    title: "Clinica de Medicina de Famalicão",
    img: "assets/portfolio/web/clinicamedicinafamalicao.png",
    desc: "",
  },
  {
    id: 12,
    type: "web",
    featured: false,
    title: "IncentivoPT",
    img: "assets/portfolio/web/incentivopt.png",
    desc: "",
  },
  {
    id: 13,
    type: "mobile",
    featured: true,
    title: "Viver Barcelos",
    img: "assets/portfolio/mobile/viverBarcelos.jpg",
    desc: "",
  },
  {
    id: 14,
    type: "mobile",
    featured: true,
    title: "TempoApp",
    img: "assets/portfolio/mobile/tempoApp.jpg",
    desc: "Uma aplicação simples criada no decorrer de uma formação.",
  },
  {
    id: 15,
    type: "design",
    featured: false,
    title: "Porta Canetas 3D",
    img: "assets/portfolio/design/portacanetas.jpg",
    desc: "",
  },
  {
    id: 16,
    type: "branding",
    featured: false,
    title: "PhotoCelos",
    img: "assets/portfolio/branding/photocelos.png",
    desc: "",
  },
];

export const worksData = [
  {
    id: 1,
    icon: "./assets/mobile.png",
    title: "Viver Barcelos",
    desc: "lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    img: "./assets/portfolio/mobile/viverBarcelos.jpg",
  },
  {
    id: 2,
    icon: "./assets/mobile.png",
    title: "TempoApp",
    desc: "É uma aplicação mobile criada durante o período de aprendizagem de JavaScript",
    img: "./assets/portfolio/mobile/tempoApp.jpg",
  },
  {
    id: 3,
    icon: "./assets/globe.png",
    title: "Belofer",
    desc: "Belofer é um website de uma empresa do ramo do comercio de peças para a industria têxtil de Barcelos",
    img: "assets/portfolio/web/belofer.png",
  },
];

export const testemonialsData = [
  {
    id: 1,
    name: "Jorge",
    title: "DOTE INVESTE, LDA",
    img: "assets/avatar.png",
    icon: "assets/youtube.png",
    desc: "De salientar a rapidez e a intercomunicabilidade em todo processo de criação.",
    featured: false,
  },
  {
    id: 2,
    name: "PRESIDENTE",
    title: "MOTOCAVAQUINHOS",
    img: "assets/avatar.png",
    icon: "assets/youtube.png",
    desc: "Um site barato, rápido e agradável.",
    featured: true,
  },
];

export const topCardsInfo = [
  {
    id: 1,
    icon: "./assets/pencil-and-ruler.png",
    title: "Branding",
    desc: "Pensamos e criamos a imagem da sua empresa",
  },
  {
    id: 2,
    icon: "./assets/computer.png",
    title: "Website",
    desc: "A identidade da sua empresa com elegância",
  },
  {
    id: 3,
    icon: "./assets/mobile-phone.png",
    title: "Mobile",
    desc: "A ideia do seu negócio ao alcance de todos",
  },
  {
    id: 4,
    icon: "./assets/megaphone.png",
    title: "Marketing",
    desc: "Ative a pegada digital do seu negócio",
  },
];
